version: "3.9"

services:
  todo-server:
    image: todo-server:0.0.0
    container_name: todo-server
    ports:
      - "3000:3000"

  todo-client:
    image: todo-client:0.0.0
    container_name: todo-client
    ports:
      - "8080:8080"
    depends_on:
      - todo-server
