version: "3.9"

services:
  todo-server:
    build: ./server
    container_name: todo-server
    environment:
      MONGO_DB: ${MONGO_DB}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3000:3000"

  todo-client:
    build: ./client
    container_name: todo-client
    ports:
      - "8080:8080"
    depends_on:
      - todo-server
